name: Deploy Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'hello-world/**'

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: '3'

      - name: Package Helm chart
        run: helm package hello-world -d hello-world/

      - name: Deploy Helm chart to Kubernetes
        run: |
          helm upgrade --install your-release-name hello-world/hello-world-*.tgz \
            --namespace helm \
            --set image.tag=$GITHUB_SHA

        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          GITHUB_SHA: ${{ github.sha }}
