name: Deploy Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'hello-world/values.yaml'

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Create the ~/.kube directory if it doesn't exist
      - name: Create kube directory
        run: mkdir -p ~/.kube

      # Set up kubectl using the provided KUBECONFIG secret
      - name: Set up kubectl
        run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Verify kubectl setup
        run: kubectl version

      # Download and install Helm
      - name: Download Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      # Package Helm chart
      - name: Package Helm chart
        run: helm package hello-world -d hello-world/

      # Check if namespace exists before creating it
      - name: Check if namespace exists
        id: check_namespace
        run: |
          if kubectl get namespace helm >/dev/null 2>&1; then
            echo "::set-output name=namespace_exists::true"
          else
            echo "::set-output name=namespace_exists::false"
          fi

      # Create namespace only if it doesn't already exist
      - name: Create namespace
        if: steps.check_namespace.outputs.namespace_exists != 'true'
        run: kubectl create namespace helm

      # Deploy Helm chart to Kubernetes
      - name: Deploy Helm chart to Kubernetes
        run: |
          helm upgrade --install helm-release hello-world/hello-world-*.tgz \
            --namespace helm

        env:
          GITHUB_SHA: ${{ github.sha }}
